---
title: "Hydrogenase Read Annotation"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
    theme: sandstone
---

```{r, include=FALSE,message=FALSE}
if(exists("snakemake")){
  database.file <- snakemake@input[["db"]]
  hits.file = snakemake@input[["hits"]]
  commonscript.file = snakemake@input[["commons"]]
  readanno_sampled_overview.file = snakemake@input[["readanno_sampled_overview"]]
  threads=snakemake@threads
}else{
  database.file = "/run/user/2496/gvfs/sftp:host=highmem1/data1/2019_LJ_data/bachelor_thesis/metadiet/output/databases/readanno/prot/hyddb.tsv"
  hits.file = "/run/user/2496/gvfs/sftp:host=highmem1/data1/2019_LJ_data/bachelor_thesis/metadiet/output/Analysis/read_annotation/hyddb/hyddb_combineddata.tsv"
  readanno_sampled_overview.file = "/run/user/2496/gvfs/sftp:host=highmem1/data1/2019_LJ_data/bachelor_thesis/metadiet/output/Analysis/sequence_data/readanno_sampled/readanno_sampled_overview.tsv"
  commonscript.file = "commonReport.R"
  threads=NA
}
taxcols=c("superkingdom","phylum","class","order","family","genus","species")
files = c(hits.file,database.file)
source(commonscript.file)
commonOptions(threads)


readanno_sampled_overview = fread(readanno_sampled_overview.file)
hits <- fread(hits.file)
database <- fread(database.file)
hits = rbind(hits,cbind(sample="Database",database),fill=T)
hits[,HydrogenaseGroup:=sapply(HydrogenaseClass,function(x)sub("\\[(.+)\\].+","\\1",x))]

hyddat = hits[,.N,by=c("sample",taxcols,"HydrogenaseClass","HydrogenaseGroup","PredictedActivity","PredictedOxyTolerance")]
```

Overview
=================

Row
--------------------------------------

### Application Note

The researchers behind the [HydDB project] provide a way to classify hydrogenases and tried to assign functions to these subgroups. While their classification process still involves a BLAST search, they predict the center ion of the hydrogenase by searching using position specific scoring matrices and construct a network of sequence similarities base on the BLAST e value with cutoff values for most classes. The bin annotation later in the workflow uses the online version of the classifier. For the short reads a [DIAMOND BLASTX](https://github.com/bbuchfink/diamond) reference has been constructed from the sequences in the database.

> Rendered at: `r Sys.time()`.

Row
--------------------------------------

### File Note

```{r}
knitr::kable(genInfoBlock(files))
```
> The table shows the files which have been used to generate this report.



Row
--------------------------------------

### Center Ion

```{r}
dat=hyddat[,.(N=sum(N)),by=c("sample","superkingdom","HydrogenaseGroup")]
dat[,rel:=N/sum(N)*100,by="sample"]
ggplotly(ggplot(dat)+aes_string(x="sample",y="rel",fill="HydrogenaseGroup")+ geom_bar(stat="identity")+ xlab("Sample") + scale_y_continuous(labels = function(x) paste0(x, "%"))+ ylab("Percentage of classified Reads") + labs(fill="Ion") + facet_grid(cols=vars(superkingdom))+theme(axis.text.x = element_text(angle = 33)+facet_grid(cols=vars("superkingdom"))))
```

> The distribution of the ion centers among the samples and domains.

### Actvity

```{r}
dat=hyddat[,.(N=sum(N)),by=c("sample","PredictedActivity","superkingdom")]
dat[,rel:=N/sum(N)*100,by=c("sample","superkingdom")]
dat=as.data.table(complete(dat,sample,superkingdom,PredictedActivity,fill=list(N=0,rel=0)))
orderHeatMap(dat,"sample",field = "rel",grouping = "PredictedActivity")
orderHeatMap(dat,"PredictedActivity",field = "rel",grouping = "sample")
ggplotly(ggplot(dat)+aes_string(x="sample",y="PredictedActivity",fill="rel") +labs(fill="% of filtered\n Reads in Domain")+ geom_raster() + xlab("Sample") + ylab("Predicted Activity")+theme(axis.text.x = element_text(angle = 33))+facet_grid(cols=vars(superkingdom)))
```

> The distribution of the predicted hydrogenase activities. the percentage is relative to the sample and the domain!

Row
---------------------------------------------

### Oxygen sensitivity

```{r}
dat=hyddat[,.(N=sum(N)),by=c("sample","PredictedOxyTolerance","superkingdom")]
dat[,rel:=N/sum(N)*100,by=c("sample","superkingdom")]
dat=as.data.table(complete(dat,sample,superkingdom,PredictedOxyTolerance,fill=list(N=0,rel=0)))
orderHeatMap(dat,"sample",field = "rel",grouping = "PredictedOxyTolerance")
orderHeatMap(dat,"PredictedOxyTolerance",field = "rel",grouping = "sample")
ggplotly(ggplot(dat)+aes_string(x="sample",y="PredictedOxyTolerance",fill="rel") +labs(fill="% of filtered\n Reads in Domain")+ geom_raster() + xlab("Sample") + ylab("Predicted Oxygen Tolerance")+theme(axis.text.x = element_text(angle = 33))+facet_grid(cols=vars(superkingdom)))
```

> The distribution of the predicted oxygen tolerance. the percentage is relative to the sample and the domain!

Row
---------------------------------------------

### Class

```{r}
dat=hyddat[,.(N=sum(N)),by=c("sample","HydrogenaseClass")]
dat[,rel:=N/sum(N)*100,by=c("sample")]
dat=as.data.table(complete(dat,sample,HydrogenaseClass,fill=list(N=0,rel=0)))
orderHeatMap(dat,"sample",field = "rel",grouping = "HydrogenaseClass")
orderHeatMap(dat,"HydrogenaseClass",field = "rel",grouping = "sample")
ggplotly(ggplot(dat)+aes_string(x="sample",y="HydrogenaseClass",fill="rel") +labs(fill="% of filtered\n Reads")+ geom_raster() + xlab("Sample") + ylab("Predicted")+theme(axis.text.x = element_text(angle = 33)))
```

> The distribution of the HydDB hydrogenase classes.


BLAST Results
===========================

Row
---------------------------------------

```{r,results="asis",fig.width=16}
drawBlastPlots(hits[sample!="Database",],readanno_sampled_overview)
```


Taxonomy
===========================

Row
---------------------------------------

```{r,results="asis"}
drawSampleTaxplots(hyddat[sample!="Database",.(N=sum(N)),by=c("sample",taxcols)])
```
